
#pragma once
#include <array.hpp>
#include <kernel/__core.hpp>

namespace kernel {
enum class MemoryRegionType : uint8_t {
  None = 0,
  Available = 1,// Raw usable RAM for the PMM bitmap to manage
  Reserved,     // Motherboard MMIO, ACPI NVS, ROMs, or bad blocks
  ACPI_Reclaim, // Safe to reclaim ONLY after ACPI parsing is done
};

struct memory_region_t {
  uintptr_t base;
  uint64_t length;
  MemoryRegionType type;
};

enum class MappedMemoryRegionType : uint8_t {
  None = 0,
  Identity = 1,// High-half bootstrapping identity maps (low 1MB)
  KernelCore,  // The primary kernel binary segments (.text, .data, .bss)
  HalModule,   // The cross-stitched HAL binary segments
  Boot_Stack,  // The initial execution stack space
  Boot_Info    // The boot_info_t structure and command line allocations
};

struct mapped_memory_t {
  MappedMemoryRegionType type;// tracks what this virtual chunk is
  uintptr_t physical_base;    // Where it lives in real RAM
  uintptr_t virtual_base;     // Where Stage 1.5 mapped it in the high-half
  size_t length;              // Total footprint size
};

struct boot_info_t {
  uint32_t page_size;

  // Pointers to arrays generated by Stage 1.5
  kstd::array<memory_region_t, 32> memory_map;
  kstd::array<mapped_memory_t, 10> mapped_memory;
  kstd::array<char, 1024> command_line;
};
}// namespace kernel
