
#pragma once
#include <array.hpp>
#include <nomm_string.hpp>
#include <static_string.hpp>

#include <kernel/__core.hpp>
#include <kernel/memory/address.hpp>

namespace kernel {
enum class MemoryRegionType : uint8_t {
  None = 0,
  Available = 1,// Raw usable RAM for the PMM bitmap to manage
  Reserved,     // Motherboard MMIO, ACPI NVS, ROMs, or bad blocks
  ACPI_Reclaim, // Safe to reclaim ONLY after ACPI parsing is done
};

struct MemoryRegionT {
  PhysicalAddress base;
  uint64_t length;
  MemoryRegionType type;
};

enum class MappedMemoryRegionType : uint8_t {
  None = 0,
  Identity = 1,// High-half bootstrapping identity maps (low 1MB)
  KernelCore,  // The primary kernel binary segments (.text, .data, .bss)
  HalModule,   // The cross-stitched HAL binary segments
  BootStack,   // The initial execution stack space
  BootInfo     // The boot_info_t structure and command line allocations
};

struct MappedMemoryT {
  MappedMemoryRegionType type;  // tracks what this virtual chunk is
  PhysicalAddress physical_base;// Where it lives in real RAM
  VirtualAddress virtual_base;  // Where Stage 1.5 mapped it in the high-half
  size_t length;                // Total footprint size
};

struct BootModuleT {
  PhysicalAddress base_physical;
  size_t length;
  kstd::static_string<64> name;
};

struct BootSymbolsT {
  kstd::static_string<48> name;
  VirtualAddress address;
};

struct BootInfoT {
  uint32_t page_size;

  // Pointers to arrays generated by Stage 1.5
  kstd::array<MemoryRegionT, 32> memory_regions;
  kstd::array<MappedMemoryT, 10> mapped_memory;
  kstd::array<BootModuleT, 15> boot_modules;

  // TODO: This needs to be relocated elsewhere; maybe even the kernel should read it's own ELF
  kstd::array<BootSymbolsT, 2048> boot_symbols;

  kstd::static_string<1024> command_line;
};
}// namespace kernel
