#pragma once

#include <kernel/k_arch.hpp>

#define PAGING_FLAG_PRESENT 0x001
#define PAGING_FLAG_WRITE 0x002
#define PAGING_FLAG_USER 0x004
#define PAGING_FLAG_WRITE_THROUGH 0x008
#define PAGING_FLAG_CACHE_DISABLE 0x010
#define PAGING_FLAG_ACCESSED 0x020
#define PAGING_FLAG_LARGER_PAGES 0x040
#define PAGING_FLAG_OS_AVAILABLE 0xE00
#define PAGING_FLAG_NO_EXECUTE (1 << 63)

#define PAGING_FLAGS_KERNEL_PAGE (PAGING_FLAG_PRESENT | PAGING_FLAG_WRITE)
#define PAGING_FLAGS_USER_PAGE (PAGING_FLAG_PRESENT | PAGING_FLAG_WRITE | PAGING_FLAG_USER)

constexpr int PAGING_PAGE_SIZE = 0x1000;
constexpr int PAGING_PAGE_BOUNDARY = 0x1000;

#define PAGING_KERNEL_OFFSET 0xffffffff80000000
#define PAGING_VIRTUAL_OFFSET 0xffff800000000000

#define GDT_DESCRIPTOR_SIZE 0x08
